/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CreditController;
import dao.DBException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Credit;
import model.Utils;
import uteis.GerenciadorIntegra;

/**
 *
 * @author jairo
 */
public class CreditView extends javax.swing.JFrame {

    /**
     * Creates new form ProviderView
     */
    private CreditController controlador;
    
    public CreditView() {
        initComponents();
            
        this.setLocationRelativeTo(null);

        this.controlador = new CreditController();

        preencheTabela();
    }
    
     public void preencheTabela() {

        for (int i = 0; i < this.controlador.getCreditList().size(); i++) {

            ((DefaultTableModel) this.CreditTable.getModel()).addRow(
                    new Object[]{
                        this.controlador.getCreditList().get(i).getDescription(),
                        Utils.formatarData(this.controlador.getCreditList().get(i).getSale_date()),
                        Utils.formatarData(this.controlador.getCreditList().get(i).getDue_date()),
                        Utils.formatarData(this.controlador.getCreditList().get(i).getPayment_date()),
                        this.controlador.getCreditList().get(i).getValue(),
                        this.controlador.getCreditList().get(i).getValue_paid(),
                        this.controlador.getCreditList().get(i).isPaid_out(),
                        this.controlador.getCreditList().get(i).getNote(),
                        this.controlador.getCreditList().get(i).getClient_id(),
                  }
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CreditTable = new javax.swing.JTable();
        ButtonDelete = new javax.swing.JToggleButton();
        ButtonBack = new javax.swing.JToggleButton();
        ButtonEdit = new javax.swing.JToggleButton();
        Title = new javax.swing.JLabel();
        ButtonNew = new javax.swing.JToggleButton();
        Exportar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreditTable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CreditTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Data de Venda", "Data de Vencimento", "Data de Pagamento", "Valor", "Valor Pago", "Pago", "Observação", "Clientes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CreditTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(CreditTable);

        ButtonDelete.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        ButtonDelete.setText("Excluir");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        ButtonBack.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        ButtonBack.setText("Voltar");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        ButtonEdit.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        ButtonEdit.setText("Editar");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        Title.setText("Creditos:");

        ButtonNew.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        ButtonNew.setText("Novo");
        ButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNewActionPerformed(evt);
            }
        });

        Exportar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        Exportar.setText("Exportar");
        Exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1079, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(ButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exportar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(Title)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonDelete)
                    .addComponent(ButtonEdit)
                    .addComponent(ButtonBack)
                    .addComponent(ButtonNew)
                    .addComponent(Exportar))
                .addGap(19, 19, 19))
        );

        setSize(new java.awt.Dimension(1107, 546));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        int posicao = CreditTable.getSelectedRow();
        int idSelected = controlador.getCreditList().get(posicao).getId();
        int resposta = JOptionPane.showConfirmDialog(null, "Você realmente deseja deletar este item?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
        
        if(resposta == JOptionPane.YES_OPTION){
            try {
                
                controlador.excluir(idSelected);
                DefaultTableModel modelo = (DefaultTableModel) CreditTable.getModel();
                modelo.setNumRows(0);
                preencheTabela();
                JOptionPane.showMessageDialog(rootPane, "Exclusão efetuada."); 
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Não foi possivel excluir esse item.", "Delete Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        FMenu menuScreen  = new FMenu();
        
        menuScreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonBackActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        int posicao = CreditTable.getSelectedRow();
        int idSelected = controlador.getCreditList().get(posicao).getId();
        
        
        try {
            EditCreditView editScreen = new EditCreditView();
            this.controlador.buscarPorId(posicao);
            editScreen.setController(this.controlador);
            editScreen.setVisible(true);
            dispose();
        } catch (DBException ex) {
            Logger.getLogger(DebitsView.class.getName()).log(Level.SEVERE, null, ex);
        }        
     
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void ButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNewActionPerformed
        RegisterCreditView registerScreen = null;
        try {
            registerScreen = new RegisterCreditView();
        } catch (DBException ex) {
            Logger.getLogger(CreditView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        registerScreen.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonNewActionPerformed

    private void ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportarActionPerformed
        try {
            ArrayList<Credit> lista = new ArrayList<Credit>();
            
            for (int i = 0 ; i < this.controlador.getCreditList().size(); i++ ){
                lista.add(new Credit(
                        this.controlador.getCreditList().get(i).getId(),
                        this.controlador.getCreditList().get(i).getSale_date(),
                        this.controlador.getCreditList().get(i).getDue_date(),
                        this.controlador.getCreditList().get(i).getPayment_date(),
                        this.controlador.getCreditList().get(i).getValue(),
                        this.controlador.getCreditList().get(i).getValue_paid(),
                        this.controlador.getCreditList().get(i).getDescription(),
                        this.controlador.getCreditList().get(i).getNote(),
                        this.controlador.getCreditList().get(i).getClient_id()
                ));
                
            }
            
            GerenciadorIntegra.produzDadosIntegracao(1, lista);
            JOptionPane.showMessageDialog(rootPane, "Dados exportados com sucesso");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao exportar os dados.", "Export Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Credit.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_ExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ButtonBack;
    private javax.swing.JToggleButton ButtonDelete;
    private javax.swing.JToggleButton ButtonEdit;
    private javax.swing.JToggleButton ButtonNew;
    private javax.swing.JTable CreditTable;
    private javax.swing.JToggleButton Exportar;
    private javax.swing.JLabel Title;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
